# Generated by Django 6.0.4 on 2026-05-31 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('it_support', 'IT Support')], default='teacher', max_length=15, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('status_change', "Status o'zgartirish"), ('restore', 'Tiklash'), ('lesson_fix', 'Darsni tuzatish'), ('attendance_fix', 'Davomatni tuzatish'), ('password_change', "Parol o'zgartirish"), ('block', 'Bloklash'), ('unblock', 'Blokdan chiqarish'), ('salary_calc', 'Oylik hisoblash'), ('photo_review', 'Rasm tekshirish'), ('system_config', 'Tizim sozlama'), ('admin_action', 'Admin amali')], max_length=30, verbose_name='Amal turi')),
                ('target_model', models.CharField(blank=True, help_text="O'zgartirilgan model nomi (masalan: Teacher, Lesson)", max_length=100, verbose_name='Maqsad modeli')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='Maqsad ID')),
                ('target_name', models.CharField(blank=True, help_text="O'zgartirilgan ob'ekt nomi (masalan: teacher ismi)", max_length=255, verbose_name='Maqsad nomi')),
                ('description', models.TextField(blank=True, help_text="O'zgarish haqida qisqacha izoh", verbose_name='Tavsif')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name="Eski ma'lumot")),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name="Yangi ma'lumot")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Loglar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_au_created_721afe_idx'), models.Index(fields=['user'], name='accounts_au_user_id_2e9d8e_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'), models.Index(fields=['target_model'], name='accounts_au_target__be3ebd_idx')],
            },
        ),
    ]
