# Generated by Django 6.0.4 on 2026-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('status_change', "Status o'zgartirish"), ('restore', 'Tiklash'), ('lesson_fix', 'Darsni tuzatish'), ('attendance_fix', 'Davomatni tuzatish'), ('password_change', "Parol o'zgartirish"), ('block', 'Bloklash'), ('unblock', 'Blokdan chiqarish'), ('salary_calc', 'Oylik hisoblash'), ('salary_fix', 'Oylik tuzatish'), ('kpi_calc', 'KPI hisoblash'), ('kpi_fix', 'KPI tuzatish'), ('photo_review', 'Rasm tekshirish'), ('system_config', 'Tizim sozlama'), ('admin_action', 'Admin amali'), ('act_as', 'Boshqa foydalanuvchi sifatida'), ('cctv_action', 'CCTV amali')], max_length=30, verbose_name='Amal turi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('it_support', 'IT Support')], default='teacher', max_length=15, verbose_name='Role'),
        ),
    ]
