# Generated by Django 6.0.4 on 2026-06-09 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_schoolclass_deleted_at_schoolclass_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Asosiy oylik')),
                ('base_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ishlab topilgan maosh')),
                ('replacement_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="O'rinbosarlikdan kelgan haq")),
                ('replaced_out_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="O'rniga o'tilgan dars chegirmasi")),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Kechikish jarimasi')),
                ('kpi_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='KPI Ustama bonus')),
                ('kpi_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='KPI Chegirma jarima')),
                ('final_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Yakuniy to'lanadigan oylik")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('paid', "To'langan")], default='draft', max_length=15, verbose_name='Status')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Hisoblangan vaqt')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Oylik Hisoboti',
                'verbose_name_plural': 'Oylik Hisobotlari',
                'ordering': ['-year', '-month', '-final_salary'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
