# Generated by Django 5.2.9 on 2026-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='lesson_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Har bir dars uchun to'lov"),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='lessons_completed',
            field=models.IntegerField(default=0, verbose_name="O'tqazilgan darslar soni"),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='lessons_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Darslardan ishlab topilgan'),
        ),
    ]
