# Generated by Django 6.0.4 on 2026-04-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sinf nomi')),
                ('grade', models.IntegerField(verbose_name='Sinf raqami')),
                ('section', models.CharField(blank=True, max_length=5, verbose_name="Bo'lim")),
                ('capacity', models.IntegerField(default=30, verbose_name="Sig'imi")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'ordering': ['grade', 'section'],
                'unique_together': {('grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Xodim ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('on_leave', "Ta'tilda")], default='active', max_length=10, verbose_name='Status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Mutaxassislik')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ishga kirgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.schoolclass', verbose_name='Sinflar')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.subject', verbose_name='Fanlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacherlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
