# Generated by Django 6.0.4 on 2026-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kunlik maosh'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soatlik maosh'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='minute_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daqiqalik maosh'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh'),
        ),
    ]
