# Generated by Django 6.0.4 on 2026-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_daily_rate_teacher_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='floor',
            field=models.IntegerField(default=1, help_text='Nechinchi etajda joylashgan', verbose_name='Etaj'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='room',
            field=models.CharField(blank=True, help_text='Masalan: 101, 205, Lab-3', max_length=20, verbose_name='Xona raqami'),
        ),
    ]
