# Generated by Django 5.2.9 on 2026-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_schoolclass_deleted_at_schoolclass_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to='teachers.schoolclass', verbose_name='Sinflar'),
        ),
    ]
