# Generated by Django 5.2.9 on 2026-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bitta dars o'tqazgani uchun to'lanadigan summa", max_digits=10, verbose_name="Har bir dars uchun to'lov"),
        ),
    ]
