# Generated by Django 5.2.9 on 2026-08-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_lesson_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_end_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text="O'qituvchining ish kunining tugash vaqti (masalan: 17:00)", verbose_name='Ish tugash vaqti'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text="O'qituvchining ish kunining boshlanish vaqti (masalan: 08:00)", verbose_name='Ish boshlanish vaqti'),
        ),
    ]
