# Generated by Django 6.0.4 on 2026-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoproof',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt"),
        ),
        migrations.AddField(
            model_name='photoproof',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
    ]
