"""
Models for attendance app.
QR Code check-in system for teacher attendance tracking.
"""

import uuid
from django.db import models
from django.conf import settings
from teachers.models import Teacher


class QRCode(models.Model):
    """QR Code for daily check-in. Generated by admin/system."""

    code = models.UUIDField(
        default=uuid.uuid4, unique=True,
        verbose_name='QR Kod',
    )
    date = models.DateField(verbose_name='Sana')
    is_active = models.BooleanField(default=True)
    expires_at = models.DateTimeField(
        verbose_name='Muddati tugash vaqti',
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True,
        verbose_name='Yaratuvchi',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'QR Kod'
        verbose_name_plural = 'QR Kodlar'
        ordering = ['-created_at']

    def __str__(self):
        return f"QR: {self.code} ({self.date})"

    @property
    def is_expired(self):
        from django.utils import timezone
        return timezone.now() > self.expires_at


class Attendance(models.Model):
    """Teacher davomat yozuvi."""

    class Status(models.TextChoices):
        PRESENT = 'present', 'Kelgan'
        ABSENT = 'absent', 'Kelmagan'
        LATE = 'late', 'Kechikkan'
        EXCUSED = 'excused', 'Sababli'

    teacher = models.ForeignKey(
        Teacher, on_delete=models.CASCADE,
        related_name='attendances',
        verbose_name='Teacher',
    )
    date = models.DateField(verbose_name='Sana')
    check_in_time = models.DateTimeField(
        null=True, blank=True,
        verbose_name='Kirish vaqti',
    )
    check_out_time = models.DateTimeField(
        null=True, blank=True,
        verbose_name='Chiqish vaqti',
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.ABSENT,
        verbose_name='Status',
    )
    qr_code = models.ForeignKey(
        QRCode, on_delete=models.SET_NULL,
        null=True, blank=True,
        verbose_name='QR Kod',
    )
    is_late = models.BooleanField(
        default=False,
        verbose_name='Kechikkan',
    )
    late_minutes = models.IntegerField(
        default=0,
        verbose_name='Kechikish (daqiqa)',
    )
    notes = models.TextField(blank=True, verbose_name='Izoh')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Davomat'
        verbose_name_plural = 'Davomatlar'
        ordering = ['-date', '-check_in_time']
        unique_together = ['teacher', 'date']

    def __str__(self):
        return (
            f"{self.teacher.user.get_full_name()} - "
            f"{self.date} - {self.get_status_display()}"
        )
