# Generated by Django 6.0.4 on 2026-04-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Rasm fayli')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='Fayl hajmi (MB)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad qilingan')], default='pending', max_length=10, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('review_notes', models.TextField(blank=True, verbose_name='Tekshiruv izohi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_proofs', to='lessons.lesson', verbose_name='Dars')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_photos', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_proofs', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Rasm isbot',
                'verbose_name_plural': 'Rasm isbotlar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
