# Generated by Django 6.0.4 on 2026-05-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('teachers', '0002_teacher_daily_rate_teacher_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_replaced',
            field=models.BooleanField(default=False, verbose_name="O'rinbosar bilan"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='replacement_reason',
            field=models.TextField(blank=True, verbose_name="O'rinbosar sababi"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='replacement_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_lessons', to='teachers.teacher', verbose_name="O'rinbosar teacher"),
        ),
    ]
