# Generated by Django 6.0.4 on 2026-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_is_replaced_lesson_replacement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='replacement_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='none', max_length=15, verbose_name="O'rinbosar statusi"),
        ),
    ]
