# Generated by Django 5.2.9 on 2026-07-25 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_deleted_at_lesson_is_deleted_and_more'),
        ('teachers', '0005_alter_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_class_lessons', to='teachers.schoolclass', verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_subject_lessons', to='teachers.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_lessons', to='teachers.teacher', verbose_name='Teacher'),
        ),
    ]
