# Generated by Django 6.0.4 on 2026-06-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_schoolclass_deleted_at_schoolclass_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('attendance_score', models.FloatField(default=0.0, verbose_name='Davomat bali (0-100)')),
                ('lesson_score', models.FloatField(default=0.0, verbose_name="Dars o'tish bali (0-100)")),
                ('proof_score', models.FloatField(default=0.0, verbose_name='Rasm isbot bali (0-100)')),
                ('late_arrival_score', models.FloatField(default=0.0, verbose_name='Kechikmaslik bali (0-100)')),
                ('replacement_score', models.FloatField(default=0.0, verbose_name="O'rinbosarlik bali")),
                ('total_score', models.FloatField(default=0.0, verbose_name='Umumiy KPI (0-100)')),
                ('grade', models.CharField(default='F', max_length=2, verbose_name='Bahosi')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Hisoblangan vaqt')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'KPI Hisoboti',
                'verbose_name_plural': 'KPI Hisobotlari',
                'ordering': ['-year', '-month', '-total_score'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
