# Generated by Django 6.0.4 on 2026-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Sozlama kaliti')),
                ('value', models.TextField(verbose_name='Qiymat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('attendance', 'Davomat sozlamalari'), ('kpi', 'KPI sozlamalari'), ('salary', 'Maosh sozlamalari'), ('general', 'Umumiy sozlamalar')], default='general', max_length=20, verbose_name='Kategoriya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim Sozlamasi',
                'verbose_name_plural': 'Tizim Sozlamalari',
                'ordering': ['category', 'key'],
            },
        ),
    ]
