# Generated by Django 6.0.4 on 2026-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=100, verbose_name='Kamera nomi')),
                ('location', models.CharField(max_length=200, verbose_name="O'rnatilgan joyi")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('stream_url', models.CharField(max_length=500, verbose_name='RTSP/HTTP Stream URL')),
                ('status', models.CharField(choices=[('online', 'Ishlamoqda (Online)'), ('offline', 'Ishlamayapti (Offline)'), ('maintenance', "Texnik xizmat ko'rsatish")], default='online', max_length=20, verbose_name='Status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshiruv vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCTV Kamera',
                'verbose_name_plural': 'CCTV Kameralar',
                'ordering': ['name'],
            },
        ),
    ]
