# Generated by Django 6.0.4 on 2026-04-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Xona raqami')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='teachers.schoolclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='teachers.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('scheduled_start', models.TimeField(verbose_name='Rejalashtirilgan boshlanish')),
                ('scheduled_end', models.TimeField(verbose_name='Rejalashtirilgan tugash')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy boshlanish')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy tugash')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('in_progress', 'Darsda'), ('completed', 'Tugagan'), ('cancelled', 'Bekor qilingan'), ('missed', "O'tilmagan")], default='scheduled', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Xona')),
                ('started_late', models.BooleanField(default=False, verbose_name='Kech boshlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.schoolclass', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.teacher', verbose_name='Teacher')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessonschedule', verbose_name='Jadval')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-date', 'scheduled_start'],
                'unique_together': {('teacher', 'date', 'scheduled_start')},
            },
        ),
    ]
