# Generated by Django 6.0.4 on 2026-04-27 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='QR Kod')),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(verbose_name='Muddati tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('status', models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikkan'), ('excused', 'Sababli')], default='absent', max_length=10, verbose_name='Status')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kechikkan')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.teacher', verbose_name='Teacher')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.qrcode', verbose_name='QR Kod')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
