# Generated by Django 6.0.4 on 2026-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_qrcode_date_remove_qrcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jarima summasi'),
        ),
    ]
