# Generated by Django 6.0.4 on 2026-04-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='date',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='expires_at',
        ),
    ]
